In [39]:
import numpy as np
import pandas as pd
data=pd.read_csv('gurgaon.csv')
data.columns

/tmp/ipykernel_108669/2495710828.py:3: DtypeWarning: Columns (66) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv('gurgaon.csv')

Index(['PROP_ID', 'PHOTO_URL', 'MEDIUM_PHOTO_URL', 'PREFERENCE', 'DESCRIPTION',
       'PROPERTY_TYPE', 'CITY', 'LOCALITY', 'TRANSACT_TYPE', 'OWNTYPE',
       'BEDROOM_NUM', 'BATHROOM_NUM', 'BALCONY_NUM', 'PRICE_PER_UNIT_AREA',
       'FURNISH', 'FACING', 'AGE', 'FLOOR_NUM', 'TOTAL_FLOOR', 'FEATURES',
       'REGISTER_DATE', 'PROP_NAME', 'MIN_PRICE', 'MAX_PRICE', 'PRICE_SQFT',
       'LISTING', 'BUILDING_ID', 'CARPET_SQFT', 'SUPERBUILTUP_SQFT',
       'BROKERAGE', 'MAP_DETAILS', 'FSL_Data', 'MIN_AREA_SQFT',
       'MAX_AREA_SQFT', 'FORMATTED', 'AMENITIES', 'TOP_USPS', 'PD_URL',
       'EXPIRY_DATE', 'GROUP_NAME', 'AREA', 'PRICE', 'PROP_HEADING',
       'PROP_DETAILS_URL', 'CLASS_HEADING', 'CLASS_LABEL', 'SECONDARY_TAGS',
       'PROPERTY_IMAGES', 'THUMBNAIL_IMAGES', 'TOTAL_LANDMARK_COUNT',
       'FORMATTED_LANDMARK_DETAILS', 'CONTACT_NAME', 'CONTACT_COMPANY_NAME',
       'DEALER_PHOTO_URL', 'SOCIETY_NAME', 'BUILDING_NAME', 'CITY_ID',
       'LOCALITY_WO_CITY', 'profile', 'xid', 'metadata', 'location',
       'BUILTUP_SQFT', 'SUPER_SQFT', 'COMMON_FURNISHING_ATTRIBUTES',
       'QUALITY_SCORE', 'FURNISHING_ATTRIBUTES'],
      dtype='object')

In [40]:
import numpy as np
import pandas as pd
df=pd.read_csv('gurgaon.csv',usecols=[
'MAP_DETAILS',
'CARPET_SQFT',
"PREFERENCE",
"PROPERTY_TYPE",
'MAX_PRICE',
'SUPERBUILTUP_SQFT',
'BEDROOM_NUM', 
'BATHROOM_NUM',
'BALCONY_NUM',
'FACING', 'AGE',
"MAP_DETAILS",
"LOCALITY_WO_CITY"
])
#PRICE_SQFT will be no more effective as we have CARPET_SQFT
#Property Price=Carpet Area × Price Per Sq Ft

In [41]:
df.columns

Index(['PREFERENCE', 'PROPERTY_TYPE', 'BEDROOM_NUM', 'BATHROOM_NUM',
       'BALCONY_NUM', 'FACING', 'AGE', 'MAX_PRICE', 'CARPET_SQFT',
       'SUPERBUILTUP_SQFT', 'MAP_DETAILS', 'LOCALITY_WO_CITY'],
      dtype='object')

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10704 entries, 0 to 10703
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   PREFERENCE         10704 non-null  object
 1   PROPERTY_TYPE      10704 non-null  object
 2   BEDROOM_NUM        10511 non-null  float64
 3   BATHROOM_NUM       10704 non-null  int64
 4   BALCONY_NUM        10501 non-null  float64
 5   FACING             10704 non-null  int64
 6   AGE                10704 non-null  int64
 7   MAX_PRICE          10704 non-null  int64
 8   CARPET_SQFT        6539 non-null   float64
 9   SUPERBUILTUP_SQFT  6712 non-null   float64
 10  MAP_DETAILS        10704 non-null  object
 11  LOCALITY_WO_CITY   10704 non-null  object
dtypes: float64(4), int64(4), object(4)
memory usage: 1003.6+ KB

In [43]:
df=df[df["PREFERENCE"]=='S']
df.head()

,PREFERENCE,PROPERTY_TYPE,BEDROOM_NUM,BATHROOM_NUM,BALCONY_NUM,FACING,AGE,MAX_PRICE,CARPET_SQFT,SUPERBUILTUP_SQFT,MAP_DETAILS,LOCALITY_WO_CITY
0,S,Residential Apartment,4.0,4,4.0,1,2,26300000,3000.0,3434.0,"{'LATITUDE': '28.4065341', 'LONGITUDE': '76.96...",Sector 84
1,S,Residential Apartment,4.0,4,3.0,1,1,36000000,1700.0,2870.0,"{'LATITUDE': '28.3889069', 'LONGITUDE': '76.95...",Sector 81
3,S,Residential Apartment,3.0,3,3.0,0,1,38500000,NaN,2802.0,"{'LATITUDE': '28.518677', 'LONGITUDE': '77.015...",Sector 112
5,S,Residential Apartment,3.0,4,4.0,2,1,19500000,NaN,2290.0,"{'LATITUDE': '28.47844', 'LONGITUDE': '76.9861...",Sector 104
7,S,Residential Apartment,2.0,2,3.0,3,6,16200000,NaN,1400.0,"{'LATITUDE': '28.4164', 'LONGITUDE': '77.01262...",Sector 74

In [44]:

df=pd.get_dummies(df,columns=['PROPERTY_TYPE'],dtype=int)
df

,PREFERENCE,BEDROOM_NUM,BATHROOM_NUM,BALCONY_NUM,FACING,AGE,MAX_PRICE,CARPET_SQFT,SUPERBUILTUP_SQFT,MAP_DETAILS,LOCALITY_WO_CITY,PROPERTY_TYPE_Independent House/Villa,PROPERTY_TYPE_Independent/Builder Floor,PROPERTY_TYPE_Residential Apartment,PROPERTY_TYPE_Residential Land
0,S,4.0,4,4.0,1,2,26300000,3000.0,3434.0,"{'LATITUDE': '28.4065341', 'LONGITUDE': '76.96...",Sector 84,0,0,1,0
1,S,4.0,4,3.0,1,1,36000000,1700.0,2870.0,"{'LATITUDE': '28.3889069', 'LONGITUDE': '76.95...",Sector 81,0,0,1,0
3,S,3.0,3,3.0,0,1,38500000,NaN,2802.0,"{'LATITUDE': '28.518677', 'LONGITUDE': '77.015...",Sector 112,0,0,1,0
5,S,3.0,4,4.0,2,1,19500000,NaN,2290.0,"{'LATITUDE': '28.47844', 'LONGITUDE': '76.9861...",Sector 104,0,0,1,0
7,S,2.0,2,3.0,3,6,16200000,NaN,1400.0,"{'LATITUDE': '28.4164', 'LONGITUDE': '77.01262...",Sector 74,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10699,S,3.0,2,3.0,3,6,25000000,NaN,2103.0,"{'LATITUDE': '28.3889069', 'LONGITUDE': '76.95...",Sector 81,0,0,1,0
10700,S,3.0,2,4.0,5,5,13500000,NaN,NaN,"{'LATITUDE': '28.39661', 'LONGITUDE': '76.9728...",Sector 83,0,0,1,0
10701,S,3.0,2,4.0,3,5,12900000,NaN,1450.0,"{'LATITUDE': '28.39661', 'LONGITUDE': '76.9728...",Sector 83,0,0,1,0
10702,S,3.0,2,4.0,3,5,13000000,NaN,1450.0,"{'LATITUDE': '28.39661', 'LONGITUDE': '76.9728...",Sector 83,0,0,1,0
10703,S,3.0,3,3.0,1,5,48000000,NaN,3200.0,"{'LATITUDE': '28.3990776', 'LONGITUDE': '77.10...",Sector 63A,0,1,0,0

In [45]:
df['SECTOR_NUMBER'] = df['LOCALITY_WO_CITY'].str.extract(r'(\d+)').astype(float).astype('Int64')

In [46]:
df.head()

,PREFERENCE,BEDROOM_NUM,BATHROOM_NUM,BALCONY_NUM,FACING,AGE,MAX_PRICE,CARPET_SQFT,SUPERBUILTUP_SQFT,MAP_DETAILS,LOCALITY_WO_CITY,PROPERTY_TYPE_Independent House/Villa,PROPERTY_TYPE_Independent/Builder Floor,PROPERTY_TYPE_Residential Apartment,PROPERTY_TYPE_Residential Land,SECTOR_NUMBER
0,S,4.0,4,4.0,1,2,26300000,3000.0,3434.0,"{'LATITUDE': '28.4065341', 'LONGITUDE': '76.96...",Sector 84,0,0,1,0,84
1,S,4.0,4,3.0,1,1,36000000,1700.0,2870.0,"{'LATITUDE': '28.3889069', 'LONGITUDE': '76.95...",Sector 81,0,0,1,0,81
3,S,3.0,3,3.0,0,1,38500000,NaN,2802.0,"{'LATITUDE': '28.518677', 'LONGITUDE': '77.015...",Sector 112,0,0,1,0,112
5,S,3.0,4,4.0,2,1,19500000,NaN,2290.0,"{'LATITUDE': '28.47844', 'LONGITUDE': '76.9861...",Sector 104,0,0,1,0,104
7,S,2.0,2,3.0,3,6,16200000,NaN,1400.0,"{'LATITUDE': '28.4164', 'LONGITUDE': '77.01262...",Sector 74,0,0,1,0,74

In [47]:
df.drop(columns=['PREFERENCE','LOCALITY_WO_CITY'],inplace=True)
df

,BEDROOM_NUM,BATHROOM_NUM,BALCONY_NUM,FACING,AGE,MAX_PRICE,CARPET_SQFT,SUPERBUILTUP_SQFT,MAP_DETAILS,PROPERTY_TYPE_Independent House/Villa,PROPERTY_TYPE_Independent/Builder Floor,PROPERTY_TYPE_Residential Apartment,PROPERTY_TYPE_Residential Land,SECTOR_NUMBER
0,4.0,4,4.0,1,2,26300000,3000.0,3434.0,"{'LATITUDE': '28.4065341', 'LONGITUDE': '76.96...",0,0,1,0,84
1,4.0,4,3.0,1,1,36000000,1700.0,2870.0,"{'LATITUDE': '28.3889069', 'LONGITUDE': '76.95...",0,0,1,0,81
3,3.0,3,3.0,0,1,38500000,NaN,2802.0,"{'LATITUDE': '28.518677', 'LONGITUDE': '77.015...",0,0,1,0,112
5,3.0,4,4.0,2,1,19500000,NaN,2290.0,"{'LATITUDE': '28.47844', 'LONGITUDE': '76.9861...",0,0,1,0,104
7,2.0,2,3.0,3,6,16200000,NaN,1400.0,"{'LATITUDE': '28.4164', 'LONGITUDE': '77.01262...",0,0,1,0,74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10699,3.0,2,3.0,3,6,25000000,NaN,2103.0,"{'LATITUDE': '28.3889069', 'LONGITUDE': '76.95...",0,0,1,0,81
10700,3.0,2,4.0,5,5,13500000,NaN,NaN,"{'LATITUDE': '28.39661', 'LONGITUDE': '76.9728...",0,0,1,0,83
10701,3.0,2,4.0,3,5,12900000,NaN,1450.0,"{'LATITUDE': '28.39661', 'LONGITUDE': '76.9728...",0,0,1,0,83
10702,3.0,2,4.0,3,5,13000000,NaN,1450.0,"{'LATITUDE': '28.39661', 'LONGITUDE': '76.9728...",0,0,1,0,83
10703,3.0,3,3.0,1,5,48000000,NaN,3200.0,"{'LATITUDE': '28.3990776', 'LONGITUDE': '77.10...",0,1,0,0,63

In [48]:
import ast

In [49]:
df['MAP_DETAILS'] = df['MAP_DETAILS'].apply(ast.literal_eval)

In [50]:
df['LATITUDE'] = df['MAP_DETAILS'].apply(
    lambda x: float(x['LATITUDE'])
)

df['LONGITUDE'] = df['MAP_DETAILS'].apply(
    lambda x: float(x['LONGITUDE'])
)

In [51]:
df.drop(columns=['MAP_DETAILS'],inplace=True)

In [52]:
df

,BEDROOM_NUM,BATHROOM_NUM,BALCONY_NUM,FACING,AGE,MAX_PRICE,CARPET_SQFT,SUPERBUILTUP_SQFT,PROPERTY_TYPE_Independent House/Villa,PROPERTY_TYPE_Independent/Builder Floor,PROPERTY_TYPE_Residential Apartment,PROPERTY_TYPE_Residential Land,SECTOR_NUMBER,LATITUDE,LONGITUDE
0,4.0,4,4.0,1,2,26300000,3000.0,3434.0,0,0,1,0,84,28.406534,76.962792
1,4.0,4,3.0,1,1,36000000,1700.0,2870.0,0,0,1,0,81,28.388907,76.951328
3,3.0,3,3.0,0,1,38500000,NaN,2802.0,0,0,1,0,112,28.518677,77.015115
5,3.0,4,4.0,2,1,19500000,NaN,2290.0,0,0,1,0,104,28.478440,76.986110
7,2.0,2,3.0,3,6,16200000,NaN,1400.0,0,0,1,0,74,28.416400,77.012620
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10699,3.0,2,3.0,3,6,25000000,NaN,2103.0,0,0,1,0,81,28.388907,76.951328
10700,3.0,2,4.0,5,5,13500000,NaN,NaN,0,0,1,0,83,28.396610,76.972830
10701,3.0,2,4.0,3,5,12900000,NaN,1450.0,0,0,1,0,83,28.396610,76.972830
10702,3.0,2,4.0,3,5,13000000,NaN,1450.0,0,0,1,0,83,28.396610,76.972830
10703,3.0,3,3.0,1,5,48000000,NaN,3200.0,0,1,0,0,63,28.399078,77.102017

In [53]:
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3075 entries, 0 to 10680
Data columns (total 15 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   BEDROOM_NUM                              3075 non-null   float64
 1   BATHROOM_NUM                             3075 non-null   int64
 2   BALCONY_NUM                              3075 non-null   float64
 3   FACING                                   3075 non-null   int64
 4   AGE                                      3075 non-null   int64
 5   MAX_PRICE                                3075 non-null   int64
 6   CARPET_SQFT                              3075 non-null   float64
 7   SUPERBUILTUP_SQFT                        3075 non-null   float64
 8   PROPERTY_TYPE_Independent House/Villa    3075 non-null   int64
 9   PROPERTY_TYPE_Independent/Builder Floor  3075 non-null   int64
 10  PROPERTY_TYPE_Residential Apartment      3075 non-null   int64
 11  PROPERTY_TYPE_Residential Land           3075 non-null   int64
 12  SECTOR_NUMBER                            3075 non-null   Int64
 13  LATITUDE                                 3075 non-null   float64
 14  LONGITUDE                                3075 non-null   float64
dtypes: Int64(1), float64(6), int64(8)
memory usage: 387.4 KB

In [54]:
# df['AREA']

In [55]:
# df['AREA'] = df['AREA'].str.replace('sq.ft.', '', regex=False).str.strip()
# df['AREA'] = df['AREA'].astype(float)
# df.head()

In [58]:
df.sample(n=10)

,BEDROOM_NUM,BATHROOM_NUM,BALCONY_NUM,FACING,AGE,MAX_PRICE,CARPET_SQFT,SUPERBUILTUP_SQFT,PROPERTY_TYPE_Independent House/Villa,PROPERTY_TYPE_Independent/Builder Floor,PROPERTY_TYPE_Residential Apartment,PROPERTY_TYPE_Residential Land,SECTOR_NUMBER,LATITUDE,LONGITUDE
6765,3.0,3,4.0,5,5,11000000,887.0,1762.0,0,0,1,0,103,28.488289,76.985599
3661,4.0,4,4.0,3,6,34500000,1790.0,2872.0,0,0,1,0,81,28.388907,76.951328
1297,3.0,4,4.0,6,2,14500000,1560.0,1930.0,0,0,1,0,86,28.399895,76.931030
698,2.0,2,3.0,5,6,12000000,1300.0,1350.0,0,0,1,0,70,28.393486,77.018605
3891,4.0,6,3.0,3,1,110000000,3250.0,3800.0,0,0,1,0,48,28.424782,77.032571
10127,2.0,2,4.0,5,5,7100000,845.0,1198.0,0,0,1,0,102,28.479277,76.976095
8364,4.0,4,2.0,5,1,26000000,2500.0,2700.0,0,1,0,0,2,28.488963,77.086665
7725,3.0,3,2.0,5,6,19000000,1500.0,1727.0,0,0,1,0,67,28.386101,77.070028
7383,2.0,2,4.0,3,5,14000000,1000.0,1310.0,0,0,1,0,113,28.522621,77.025487
10389,3.0,4,4.0,3,5,49800000,1447.0,2500.0,0,0,1,0,1,28.472720,77.074940

In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['MAX_PRICE']),df['MAX_PRICE'],test_size=0.2,random_state=42)

X_train.iloc[0]

BEDROOM_NUM                                     4.0
BATHROOM_NUM                                    5.0
BALCONY_NUM                                     2.0
FACING                                          1.0
AGE                                             1.0
CARPET_SQFT                                  3000.0
SUPERBUILTUP_SQFT                            5000.0
PROPERTY_TYPE_Independent House/Villa           0.0
PROPERTY_TYPE_Independent/Builder Floor         1.0
PROPERTY_TYPE_Residential Apartment             0.0
PROPERTY_TYPE_Residential Land                  0.0
SECTOR_NUMBER                                   2.0
LATITUDE                                   28.42352
LONGITUDE                                  77.09802
Name: 1062, dtype: Float64

In [ ]:
y_train.iloc[0]

42000000

In [ ]:
from xgboost import XGBRegressor

model = XGBRegressor(random_state=42)
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

mse = mean_absolute_error(y_test,y_pred)

r2 = r2_score(y_test,y_pred)
print("mse",mse)
print("r2",r2)

mse 3179539.75
r2 0.9063718318939209

In [ ]:
# import joblib

# joblib.dump(model, "property_price_model.pkl")