In [49]:
import numpy as np
import pandas as pd
data=pd.read_csv('gurgaon.csv')
data.head()

/tmp/ipykernel_209193/2634301274.py:3: DtypeWarning: Columns (66) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv('gurgaon.csv')

,PROP_ID,PHOTO_URL,MEDIUM_PHOTO_URL,PREFERENCE,DESCRIPTION,PROPERTY_TYPE,CITY,LOCALITY,TRANSACT_TYPE,OWNTYPE,...,LOCALITY_WO_CITY,profile,xid,metadata,location,BUILTUP_SQFT,SUPER_SQFT,COMMON_FURNISHING_ATTRIBUTES,QUALITY_SCORE,FURNISHING_ATTRIBUTES
0,O71585872,https://mediacdn.99acres.com/media1/22409/13/4...,https://mediacdn.99acres.com/media1/22409/13/4...,S,4 bhk flat for resale in alpha corp gurgaon one,Residential Apartment,Gurgaon,Sector 84 Gurgaon,1.0,1,...,Sector 84,"{'CONTACT_NAME': 'gaurav khosla', 'CONTACT_COM...","{'PROJECTID': 5096, 'PROJ_NAME': 'Alpha Corp G...","{'PROP_PHOTO_COUNT': '4', 'PROP_VIDEO_COUNT': ...","{'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDIN...",NaN,NaN,NaN,NaN,NaN
1,T71585466,https://mediacdn.99acres.com/media1/22425/6/44...,https://mediacdn.99acres.com/media1/22425/6/44...,S,"Explore dlf ultima, an upscale ready-To-Move h...",Residential Apartment,Gurgaon,Sector 81 Gurgaon,1.0,1,...,Sector 81,"{'CONTACT_NAME': 'Kamal', 'CONTACT_COMPANY_NAM...","{'PROJECTID': 7182, 'PROJ_NAME': 'DLF The Ulti...","{'PROP_PHOTO_COUNT': '4', 'PROP_VIDEO_COUNT': ...","{'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDIN...",NaN,NaN,NaN,NaN,NaN
2,D71549524,https://mediacdn.99acres.com/media1/22386/13/4...,https://mediacdn.99acres.com/media1/22386/13/4...,R,A 3 bhk flat for rent in sector 66 gurgaon clo...,Residential Apartment,Gurgaon,Sector 66 Gurgaon,NaN,0,...,Sector 66,"{'CONTACT_NAME': 'Sandeep', 'CONTACT_COMPANY_N...","{'PROJECTID': 19, 'PROJ_NAME': 'Emaar MGF The ...","{'PROP_PHOTO_COUNT': '1', 'PROP_VIDEO_COUNT': ...","{'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDIN...",1920.00,NaN,NaN,NaN,NaN
3,I71493958,https://mediacdn.99acres.com/media1/22353/14/4...,https://mediacdn.99acres.com/media1/22353/14/4...,S,Looking for a 3 bhk property for purchase in g...,Residential Apartment,Gurgaon,Sector 112 Gurgaon,1.0,1,...,Sector 112,"{'CONTACT_NAME': 'Kohli', 'CONTACT_COMPANY_NAM...","{'PROJECTID': 4342, 'PROJ_NAME': 'Experion Win...","{'PROP_PHOTO_COUNT': '1', 'PROP_VIDEO_COUNT': ...","{'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDIN...",2225.56,NaN,NaN,NaN,NaN
4,H71479412,https://mediacdn.99acres.com/media1/22352/4/44...,https://mediacdn.99acres.com/media1/22352/4/44...,R,This 4 bhk flat in sector 104 gurgaon is avail...,Residential Apartment,Gurgaon,Sector 104 Gurgaon,NaN,0,...,Sector 104,"{'CONTACT_NAME': 'Kohli', 'CONTACT_COMPANY_NAM...","{'PROJECTID': 25860, 'PROJ_NAME': 'ATS Triumph...","{'PROP_PHOTO_COUNT': '14', 'PROP_VIDEO_COUNT':...","{'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDIN...",NaN,NaN,NaN,NaN,NaN

In [50]:
import numpy as np
import pandas as pd
df=pd.read_csv('gurgaon.csv',usecols=[
'MAP_DETAILS',
'CARPET_SQFT',
"PREFERENCE",
"PROPERTY_TYPE",
'MAX_PRICE',
'SUPERBUILTUP_SQFT',
'BEDROOM_NUM', 
'BATHROOM_NUM',
'BALCONY_NUM',
'FACING', 'AGE',
"MAP_DETAILS",
"LOCALITY_WO_CITY"
])
#PRICE_SQFT will be no more effective as we have CARPET_SQFT
#Property Price=Carpet Area × Price Per Sq Ft

In [51]:
df.columns

Index(['PREFERENCE', 'PROPERTY_TYPE', 'BEDROOM_NUM', 'BATHROOM_NUM',
       'BALCONY_NUM', 'FACING', 'AGE', 'MAX_PRICE', 'CARPET_SQFT',
       'SUPERBUILTUP_SQFT', 'MAP_DETAILS', 'LOCALITY_WO_CITY'],
      dtype='object')

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10704 entries, 0 to 10703
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   PREFERENCE         10704 non-null  object
 1   PROPERTY_TYPE      10704 non-null  object
 2   BEDROOM_NUM        10511 non-null  float64
 3   BATHROOM_NUM       10704 non-null  int64
 4   BALCONY_NUM        10501 non-null  float64
 5   FACING             10704 non-null  int64
 6   AGE                10704 non-null  int64
 7   MAX_PRICE          10704 non-null  int64
 8   CARPET_SQFT        6539 non-null   float64
 9   SUPERBUILTUP_SQFT  6712 non-null   float64
 10  MAP_DETAILS        10704 non-null  object
 11  LOCALITY_WO_CITY   10704 non-null  object
dtypes: float64(4), int64(4), object(4)
memory usage: 1003.6+ KB

In [53]:
df=df[df["PREFERENCE"]=='S']
df.head()

,PREFERENCE,PROPERTY_TYPE,BEDROOM_NUM,BATHROOM_NUM,BALCONY_NUM,FACING,AGE,MAX_PRICE,CARPET_SQFT,SUPERBUILTUP_SQFT,MAP_DETAILS,LOCALITY_WO_CITY
0,S,Residential Apartment,4.0,4,4.0,1,2,26300000,3000.0,3434.0,"{'LATITUDE': '28.4065341', 'LONGITUDE': '76.96...",Sector 84
1,S,Residential Apartment,4.0,4,3.0,1,1,36000000,1700.0,2870.0,"{'LATITUDE': '28.3889069', 'LONGITUDE': '76.95...",Sector 81
3,S,Residential Apartment,3.0,3,3.0,0,1,38500000,NaN,2802.0,"{'LATITUDE': '28.518677', 'LONGITUDE': '77.015...",Sector 112
5,S,Residential Apartment,3.0,4,4.0,2,1,19500000,NaN,2290.0,"{'LATITUDE': '28.47844', 'LONGITUDE': '76.9861...",Sector 104
7,S,Residential Apartment,2.0,2,3.0,3,6,16200000,NaN,1400.0,"{'LATITUDE': '28.4164', 'LONGITUDE': '77.01262...",Sector 74

In [54]:

df=pd.get_dummies(df,columns=['PROPERTY_TYPE'],dtype=int)
df

,PREFERENCE,BEDROOM_NUM,BATHROOM_NUM,BALCONY_NUM,FACING,AGE,MAX_PRICE,CARPET_SQFT,SUPERBUILTUP_SQFT,MAP_DETAILS,LOCALITY_WO_CITY,PROPERTY_TYPE_Independent House/Villa,PROPERTY_TYPE_Independent/Builder Floor,PROPERTY_TYPE_Residential Apartment,PROPERTY_TYPE_Residential Land
0,S,4.0,4,4.0,1,2,26300000,3000.0,3434.0,"{'LATITUDE': '28.4065341', 'LONGITUDE': '76.96...",Sector 84,0,0,1,0
1,S,4.0,4,3.0,1,1,36000000,1700.0,2870.0,"{'LATITUDE': '28.3889069', 'LONGITUDE': '76.95...",Sector 81,0,0,1,0
3,S,3.0,3,3.0,0,1,38500000,NaN,2802.0,"{'LATITUDE': '28.518677', 'LONGITUDE': '77.015...",Sector 112,0,0,1,0
5,S,3.0,4,4.0,2,1,19500000,NaN,2290.0,"{'LATITUDE': '28.47844', 'LONGITUDE': '76.9861...",Sector 104,0,0,1,0
7,S,2.0,2,3.0,3,6,16200000,NaN,1400.0,"{'LATITUDE': '28.4164', 'LONGITUDE': '77.01262...",Sector 74,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10699,S,3.0,2,3.0,3,6,25000000,NaN,2103.0,"{'LATITUDE': '28.3889069', 'LONGITUDE': '76.95...",Sector 81,0,0,1,0
10700,S,3.0,2,4.0,5,5,13500000,NaN,NaN,"{'LATITUDE': '28.39661', 'LONGITUDE': '76.9728...",Sector 83,0,0,1,0
10701,S,3.0,2,4.0,3,5,12900000,NaN,1450.0,"{'LATITUDE': '28.39661', 'LONGITUDE': '76.9728...",Sector 83,0,0,1,0
10702,S,3.0,2,4.0,3,5,13000000,NaN,1450.0,"{'LATITUDE': '28.39661', 'LONGITUDE': '76.9728...",Sector 83,0,0,1,0
10703,S,3.0,3,3.0,1,5,48000000,NaN,3200.0,"{'LATITUDE': '28.3990776', 'LONGITUDE': '77.10...",Sector 63A,0,1,0,0

In [55]:
df['SECTOR_NUMBER'] = df['LOCALITY_WO_CITY'].str.extract(r'(\d+)').astype(float).astype('Int64')

In [56]:
df.head()

,PREFERENCE,BEDROOM_NUM,BATHROOM_NUM,BALCONY_NUM,FACING,AGE,MAX_PRICE,CARPET_SQFT,SUPERBUILTUP_SQFT,MAP_DETAILS,LOCALITY_WO_CITY,PROPERTY_TYPE_Independent House/Villa,PROPERTY_TYPE_Independent/Builder Floor,PROPERTY_TYPE_Residential Apartment,PROPERTY_TYPE_Residential Land,SECTOR_NUMBER
0,S,4.0,4,4.0,1,2,26300000,3000.0,3434.0,"{'LATITUDE': '28.4065341', 'LONGITUDE': '76.96...",Sector 84,0,0,1,0,84
1,S,4.0,4,3.0,1,1,36000000,1700.0,2870.0,"{'LATITUDE': '28.3889069', 'LONGITUDE': '76.95...",Sector 81,0,0,1,0,81
3,S,3.0,3,3.0,0,1,38500000,NaN,2802.0,"{'LATITUDE': '28.518677', 'LONGITUDE': '77.015...",Sector 112,0,0,1,0,112
5,S,3.0,4,4.0,2,1,19500000,NaN,2290.0,"{'LATITUDE': '28.47844', 'LONGITUDE': '76.9861...",Sector 104,0,0,1,0,104
7,S,2.0,2,3.0,3,6,16200000,NaN,1400.0,"{'LATITUDE': '28.4164', 'LONGITUDE': '77.01262...",Sector 74,0,0,1,0,74

In [57]:
df.drop(columns=['PREFERENCE','LOCALITY_WO_CITY'],inplace=True)
df

,BEDROOM_NUM,BATHROOM_NUM,BALCONY_NUM,FACING,AGE,MAX_PRICE,CARPET_SQFT,SUPERBUILTUP_SQFT,MAP_DETAILS,PROPERTY_TYPE_Independent House/Villa,PROPERTY_TYPE_Independent/Builder Floor,PROPERTY_TYPE_Residential Apartment,PROPERTY_TYPE_Residential Land,SECTOR_NUMBER
0,4.0,4,4.0,1,2,26300000,3000.0,3434.0,"{'LATITUDE': '28.4065341', 'LONGITUDE': '76.96...",0,0,1,0,84
1,4.0,4,3.0,1,1,36000000,1700.0,2870.0,"{'LATITUDE': '28.3889069', 'LONGITUDE': '76.95...",0,0,1,0,81
3,3.0,3,3.0,0,1,38500000,NaN,2802.0,"{'LATITUDE': '28.518677', 'LONGITUDE': '77.015...",0,0,1,0,112
5,3.0,4,4.0,2,1,19500000,NaN,2290.0,"{'LATITUDE': '28.47844', 'LONGITUDE': '76.9861...",0,0,1,0,104
7,2.0,2,3.0,3,6,16200000,NaN,1400.0,"{'LATITUDE': '28.4164', 'LONGITUDE': '77.01262...",0,0,1,0,74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10699,3.0,2,3.0,3,6,25000000,NaN,2103.0,"{'LATITUDE': '28.3889069', 'LONGITUDE': '76.95...",0,0,1,0,81
10700,3.0,2,4.0,5,5,13500000,NaN,NaN,"{'LATITUDE': '28.39661', 'LONGITUDE': '76.9728...",0,0,1,0,83
10701,3.0,2,4.0,3,5,12900000,NaN,1450.0,"{'LATITUDE': '28.39661', 'LONGITUDE': '76.9728...",0,0,1,0,83
10702,3.0,2,4.0,3,5,13000000,NaN,1450.0,"{'LATITUDE': '28.39661', 'LONGITUDE': '76.9728...",0,0,1,0,83
10703,3.0,3,3.0,1,5,48000000,NaN,3200.0,"{'LATITUDE': '28.3990776', 'LONGITUDE': '77.10...",0,1,0,0,63

In [58]:
import ast

In [59]:
df['MAP_DETAILS'] = df['MAP_DETAILS'].apply(ast.literal_eval)

In [60]:
df['LATITUDE'] = df['MAP_DETAILS'].apply(
    lambda x: float(x['LATITUDE'])
)

df['LONGITUDE'] = df['MAP_DETAILS'].apply(
    lambda x: float(x['LONGITUDE'])
)

In [61]:
df.drop(columns=['MAP_DETAILS'],inplace=True)

In [62]:
df

,BEDROOM_NUM,BATHROOM_NUM,BALCONY_NUM,FACING,AGE,MAX_PRICE,CARPET_SQFT,SUPERBUILTUP_SQFT,PROPERTY_TYPE_Independent House/Villa,PROPERTY_TYPE_Independent/Builder Floor,PROPERTY_TYPE_Residential Apartment,PROPERTY_TYPE_Residential Land,SECTOR_NUMBER,LATITUDE,LONGITUDE
0,4.0,4,4.0,1,2,26300000,3000.0,3434.0,0,0,1,0,84,28.406534,76.962792
1,4.0,4,3.0,1,1,36000000,1700.0,2870.0,0,0,1,0,81,28.388907,76.951328
3,3.0,3,3.0,0,1,38500000,NaN,2802.0,0,0,1,0,112,28.518677,77.015115
5,3.0,4,4.0,2,1,19500000,NaN,2290.0,0,0,1,0,104,28.478440,76.986110
7,2.0,2,3.0,3,6,16200000,NaN,1400.0,0,0,1,0,74,28.416400,77.012620
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10699,3.0,2,3.0,3,6,25000000,NaN,2103.0,0,0,1,0,81,28.388907,76.951328
10700,3.0,2,4.0,5,5,13500000,NaN,NaN,0,0,1,0,83,28.396610,76.972830
10701,3.0,2,4.0,3,5,12900000,NaN,1450.0,0,0,1,0,83,28.396610,76.972830
10702,3.0,2,4.0,3,5,13000000,NaN,1450.0,0,0,1,0,83,28.396610,76.972830
10703,3.0,3,3.0,1,5,48000000,NaN,3200.0,0,1,0,0,63,28.399078,77.102017

In [63]:
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3075 entries, 0 to 10680
Data columns (total 15 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   BEDROOM_NUM                              3075 non-null   float64
 1   BATHROOM_NUM                             3075 non-null   int64
 2   BALCONY_NUM                              3075 non-null   float64
 3   FACING                                   3075 non-null   int64
 4   AGE                                      3075 non-null   int64
 5   MAX_PRICE                                3075 non-null   int64
 6   CARPET_SQFT                              3075 non-null   float64
 7   SUPERBUILTUP_SQFT                        3075 non-null   float64
 8   PROPERTY_TYPE_Independent House/Villa    3075 non-null   int64
 9   PROPERTY_TYPE_Independent/Builder Floor  3075 non-null   int64
 10  PROPERTY_TYPE_Residential Apartment      3075 non-null   int64
 11  PROPERTY_TYPE_Residential Land           3075 non-null   int64
 12  SECTOR_NUMBER                            3075 non-null   Int64
 13  LATITUDE                                 3075 non-null   float64
 14  LONGITUDE                                3075 non-null   float64
dtypes: Int64(1), float64(6), int64(8)
memory usage: 387.4 KB

In [64]:
features = [
    'BEDROOM_NUM',
    'BATHROOM_NUM',
    'BALCONY_NUM',
    'FACING',
    'AGE',
    'CARPET_SQFT',
    'SUPERBUILTUP_SQFT',
    'PROPERTY_TYPE_Independent House/Villa',
    'PROPERTY_TYPE_Independent/Builder Floor',
    'PROPERTY_TYPE_Residential Apartment',
    'PROPERTY_TYPE_Residential Land',
    'SECTOR_NUMBER',
    'LATITUDE',
    'LONGITUDE'
]

X = df[features]

In [65]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [ ]:
from sklearn.neighbors import NearestNeighbors
lat_idx = X.columns.get_loc('LATITUDE')
lon_idx = X.columns.get_loc('LONGITUDE')

# APPLY WEIGHT AFTER SCALING
X_scaled[:, lat_idx] *= 10
X_scaled[:, lon_idx] *= 10

knn = NearestNeighbors(
    n_neighbors=10,
    metric='euclidean'
)

knn.fit(X_scaled)

NearestNeighbors(metric='euclidean', n_neighbors=15)

In [67]:
selected_property = X_scaled[100].reshape(1, -1)
print(X_scaled[100])
print(selected_property)

distances, indices = knn.kneighbors(selected_property)

print(indices)
print(distances)

[ 1.1864623   1.57217656  1.12484085 -1.93003801 -0.5735825   0.20923204
  0.15872215 -0.02551137 -0.47547508  0.47650296  0.          0.18569073
 -0.71493659  0.60311802]
[[ 1.1864623   1.57217656  1.12484085 -1.93003801 -0.5735825   0.20923204
   0.15872215 -0.02551137 -0.47547508  0.47650296  0.          0.18569073
  -0.71493659  0.60311802]]
[[ 100 1652 1255 2217  397  398  801 1922 1428 1996  802 1581  552  700
   907]]
[[0.         0.38521858 0.53275172 0.84487578 0.94161454 0.95022135
  0.97309265 1.0316905  1.04169376 1.08430621 1.10172583 1.1236287
  1.17211959 1.28982138 1.29147649]]

In [68]:
recommended = data.loc[df.index[indices[0]]]

print(recommended)

        PROP_ID                                          PHOTO_URL  \
100   Y69969376  https://mediacdn.99acres.com/media1/21536/18/4...
1652  W71526454                                                NaN
1255  X71398120                                                NaN
2217  B71440278                                                NaN
397   G71626234  https://mediacdn.99acres.com/media1/22465/8/44...
398   J71626024  https://mediacdn.99acres.com/media1/22464/0/44...
801   C71232812  https://mediacdn.99acres.com/media1/22203/10/4...
1922  I71211570  https://mediacdn.99acres.com/media1/22192/2/44...
1428  P70927826  https://mediacdn.99acres.com/media1/22041/7/44...
1996  F71014146  https://mediacdn.99acres.com/media1/22085/19/4...
802   Y71232302                                                NaN
1581  W71545116  https://mediacdn.99acres.com/media1/22384/7/44...
552   J71479164  https://mediacdn.99acres.com/media1/22345/8/44...
700   I71384160  https://mediacdn.99acres.com/media1/22417/1/44...
907   G70629618  https://mediacdn.99acres.com/media1/21894/6/43...

                                       MEDIUM_PHOTO_URL PREFERENCE  \
100   https://mediacdn.99acres.com/media1/21536/18/4...          S
1652                                                NaN          S
1255                                                NaN          S
2217                                                NaN          S
397   https://mediacdn.99acres.com/media1/22465/8/44...          S
398   https://mediacdn.99acres.com/media1/22464/0/44...          S
801   https://mediacdn.99acres.com/media1/22203/10/4...          R
1922  https://mediacdn.99acres.com/media1/22192/2/44...          S
1428  https://mediacdn.99acres.com/media1/22041/7/44...          S
1996  https://mediacdn.99acres.com/media1/22085/19/4...          S
802                                                 NaN          S
1581  https://mediacdn.99acres.com/media1/22384/7/44...          S
552   https://mediacdn.99acres.com/media1/22345/8/44...          S
700   https://mediacdn.99acres.com/media1/22417/1/44...          S
907   https://mediacdn.99acres.com/media1/21894/6/43...          S

                                            DESCRIPTION  \
100   Indulge in the pinnacle of luxury living with ...
1652  Rediscover a good lifestyle in 20.5890 acres o...
1255  Situated in sector 1 imt manesar, gurgaon, the...
2217  Located in the popular residential address of ...
397   Check out this 3 bhk apartment for sale in par...
398   This beautiful 3 bhk flat in sector 99 gurgaon...
801   Puri construction 104 3bhkser best unit semi f...
1922  Spread over an area of 100 acres, experion the...
1428  Best affordable flat gated aravali view\nMain ...
1996  Discover smartly planned 3 bhk builder floor i...
802   382 sq yards, 2 side open, corner plot is avai...
1581  Shree vardhman mantra is one of the most popul...
552   Ultra luxury builder floor (East facing and pa...
700   1800 sq ft 3 bhk flat on sale in adani samsara...
907   This lovely 3 bhk apartment/flat in sector 90 ...

                  PROPERTY_TYPE     CITY              LOCALITY  TRANSACT_TYPE  \
100       Residential Apartment  Gurgaon           DLF Phase 5            1.0
1652      Residential Apartment  Gurgaon    Sector 37D Gurgaon            1.0
1255      Residential Apartment  Gurgaon  Sector 1 Imt Manesar            1.0
2217      Residential Apartment  Gurgaon     Sector 72 Gurgaon            1.0
397       Residential Apartment  Gurgaon     Sector 99 Gurgaon            1.0
398       Residential Apartment  Gurgaon     Sector 99 Gurgaon            1.0
801       Residential Apartment  Gurgaon    Sector 104 Gurgaon            NaN
1922           Residential Land  Gurgaon    Sector 108 Gurgaon            1.0
1428      Residential Apartment  Gurgaon                 Sohna            1.0
1996  Independent/Builder Floor  Gurgaon           Malibu Town            1.0
802            Residential Land  Gurgaon     Sector 63 Gurgaon            1.0
1581      Residential Apartment  Gurgaon     Sector 67 Gurgaon            1.0
552   Independent/Builder Floor  Gurgaon     Sector 56 Gurgaon            1.0
700   Independent/Builder Floor  Gurgaon     Sector 63 Gurgaon            1.0
907       Residential Apartment  Gurgaon     Sector 90 Gurgaon            1.0

      OWNTYPE  ...      LOCALITY_WO_CITY  \
100         1  ...           DLF Phase 5
1652        1  ...            Sector 37D
1255        1  ...  Sector 1 Imt Manesar
2217        1  ...             Sector 72
397         1  ...             Sector 99
398         1  ...             Sector 99
801         0  ...            Sector 104
1922        1  ...            Sector 108
1428        1  ...                 Sohna
1996        1  ...           Malibu Town
802         1  ...             Sector 63
1581        1  ...             Sector 67
552         1  ...             Sector 56
700         1  ...             Sector 63
907         1  ...             Sector 90

                                                profile  \
100   {'CONTACT_NAME': 'VIKAS NAGPAL', 'CONTACT_COMP...
1652  {'CONTACT_NAME': 'GLOBAL TIME REALTY', 'CONTAC...
1255  {'CONTACT_NAME': 'Kapil Sharma', 'CONTACT_COMP...
2217  {'CONTACT_NAME': 'Mulayam yadav', 'CONTACT_COM...
397   {'CONTACT_NAME': 'Gayatri Arya', 'CONTACT_COMP...
398   {'CONTACT_NAME': 'Gayatri Arya', 'CONTACT_COMP...
801   {'CONTACT_NAME': 'Arjun', 'CONTACT_COMPANY_NAM...
1922  {'CONTACT_NAME': 'Keshav Garg', 'CONTACT_COMPA...
1428  {'CONTACT_NAME': 'City Properties', 'CONTACT_C...
1996  {'CONTACT_NAME': 'Jasbir Singh', 'CONTACT_COMP...
802   {'CONTACT_NAME': 'One Key', 'CONTACT_COMPANY_N...
1581  {'CONTACT_NAME': 'Neeraj and Co', 'CONTACT_COM...
552   {'CONTACT_NAME': 'Ranil Group ', 'CONTACT_COMP...
700   {'CONTACT_NAME': 'Anuj', 'CONTACT_COMPANY_NAME...
907   {'CONTACT_NAME': 'Vijay Gupta', 'CONTACT_COMPA...

                                                    xid  \
100   {'PROJECTID': 27744, 'PROJ_NAME': 'DLF Westend...
1652  {'PROJECTID': 378934, 'PROJ_NAME': 'Signature ...
1255                   {'PROJECTID': 0, 'BUILDERID': 0}
2217  {'PROJECTID': 12166, 'PROJ_NAME': 'Spaze Privy...
397   {'PROJECTID': 38208, 'PROJ_NAME': 'Pareena Exp...
398   {'PROJECTID': 38208, 'PROJ_NAME': 'Pareena Exp...
801   {'PROJECTID': 5456, 'PROJ_NAME': 'Puri Emerald...
1922  {'PROJECTID': 18410, 'PROJ_NAME': 'Experion Th...
1428  {'PROJECTID': 111627, 'PROJ_NAME': 'HCBS Sport...
1996                   {'PROJECTID': 0, 'BUILDERID': 0}
802   {'PROJECTID': 368126, 'PROJ_NAME': 'Anant Raj ...
1581  {'PROJECTID': 28298, 'PROJ_NAME': 'Shree Vardh...
552                    {'PROJECTID': 0, 'BUILDERID': 0}
700   {'PROJECTID': 327995, 'PROJ_NAME': 'Adani Brah...
907                    {'PROJECTID': 0, 'BUILDERID': 0}

                                               metadata  \
100   {'PROP_PHOTO_COUNT': '12', 'PROP_VIDEO_COUNT':...
1652  {'PROP_PHOTO_COUNT': '0', 'PROP_VIDEO_COUNT': ...
1255  {'PROP_PHOTO_COUNT': '0', 'PROP_VIDEO_COUNT': ...
2217  {'PROP_PHOTO_COUNT': '0', 'PROP_VIDEO_COUNT': ...
397   {'PROP_PHOTO_COUNT': '13', 'PROP_VIDEO_COUNT':...
398   {'PROP_PHOTO_COUNT': '13', 'PROP_VIDEO_COUNT':...
801   {'PROP_PHOTO_COUNT': '9', 'PROP_VIDEO_COUNT': ...
1922  {'PROP_PHOTO_COUNT': '14', 'PROP_VIDEO_COUNT':...
1428  {'PROP_PHOTO_COUNT': '14', 'PROP_VIDEO_COUNT':...
1996  {'PROP_PHOTO_COUNT': '11', 'PROP_VIDEO_COUNT':...
802   {'PROP_PHOTO_COUNT': '0', 'PROP_VIDEO_COUNT': ...
1581  {'PROP_PHOTO_COUNT': '8', 'PROP_VIDEO_COUNT': ...
552   {'PROP_PHOTO_COUNT': '8', 'PROP_VIDEO_COUNT': ...
700   {'PROP_PHOTO_COUNT': '14', 'PROP_VIDEO_COUNT':...
907   {'PROP_PHOTO_COUNT': '5', 'PROP_VIDEO_COUNT': ...

                                               location  BUILTUP_SQFT  \
100   {'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDIN...           NaN
1652  {'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDIN...           NaN
1255  {'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDIN...        2024.0
2217  {'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDIN...           NaN
397   {'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDIN...           NaN
398   {'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDIN...           NaN
801   {'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDIN...           NaN
1922  {'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDIN...           NaN
1428  {'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDIN...           NaN
1996  {'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDIN...           NaN
802   {'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDIN...           NaN
1581  {'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDIN...           NaN
552   {'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDIN...        1700.0
700   {'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDIN...        1800.0
907   {'CITY': '8', 'CITY_NAME': 'Gurgaon', 'BUILDIN...         650.0

      SUPER_SQFT COMMON_FURNISHING_ATTRIBUTES  QUALITY_SCORE  \
100          NaN                          NaN            NaN
1652         NaN                          NaN            NaN
1255         NaN                          NaN            NaN
2217         NaN                          NaN            NaN
397          NaN                          NaN            NaN
398          NaN                          NaN            NaN
801          NaN                          NaN            NaN
1922      3231.0                          NaN            NaN
1428         NaN                          NaN            NaN
1996         NaN                          NaN            NaN
802       3438.0                          NaN            NaN
1581         NaN                          NaN            NaN
552          NaN                          NaN            NaN
700          NaN                          NaN            NaN
907          NaN                          NaN            NaN

     FURNISHING_ATTRIBUTES
100                    NaN
1652                   NaN
1255                   NaN
2217                   NaN
397                    NaN
398                    NaN
801                    NaN
1922                   NaN
1428                   NaN
1996                   NaN
802                    NaN
1581                   NaN
552                    NaN
700                    NaN
907                    NaN

[15 rows x 67 columns]

In [69]:
from joblib import dump
artifact = {
    "knn": knn,
    "scaler": scaler,
    "features": features,
    "training_index": df.index.tolist(),
    "data": data.loc[df.index].reset_index(drop=True)
}

dump(artifact, "recommendation.pkl")

['recommendation.pkl']